service: editor
runtime: ruby26

entrypoint: bundle exec ruby app.rb -p 8080

instance_class: F2

handlers:
- url: /(main\.dart\.js|favicon\.ico|styles\.css)
  static_files: public/\1
  upload: public/(main\.dart\.js|favicon\.ico|styles\.css)
  expiration: 10m  # Small files & JS gets updated frequently
- url: /fonts
  static_dir: public/fonts
  expiration: 7d  # Unlikely to update fonts without renaming
- url: /assets
  static_dir: public/assets
  expiration: 1h  # Could update images without renaming
