name: reshma-website-server
author: "Timofey Peshin"

dependencies:
- base == 4.12.0.0
- warp >= 3.3
- wai >= 3.2
- http-types >= 0.12.3
- bytestring >= 0.10
- mime-types >= 0.1
- text >= 1.2

library:
  source-dirs: src

executables:
  reshma-website-server-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reshma-website-server
