load("//build_rules:dart.bzl", "dart_library")

dart_library(
    name = "editor",
    pub_deps = [
        "angular: ^6.0.1",
        "bootstrap_sass: any",
    ],
    pub_dev_deps = [
        "build_runner: ^1.10.0",
        "build_web_compilers: ^2.11.0",
        "pedantic: ^1.9.0",
        "sass_builder: ^2.1.3",
    ],
    deps = [
        "//coreweb",
        "//proto:rz_schema_dart_proto",
    ],
)
