name: rz.editor
description: Editor for reshmawebsite.

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  angular: ^6.0.1
  bootstrap_sass: any
  rz.proto:
    path: local_packages/rz.proto
  rz.coreweb:
    path: local_packages/rz.coreweb

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
  sass_builder: ^2.1.3
