load("//build_rules:dart_proto_library.bzl", "dart_proto_library")

package(
    default_visibility = ["//visibility:public"],
)

dart_proto_library(
    name = "rz_schema",
    srcs = ["rz_schema.proto"],
)
